apiVersion: v1
kind: PersistentVolume
metadata:
  name: aspnet-pv
  labels:
    type: local-pv # Label to match the PVC
spec:
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/myvolume"
  storageClassName: manual