apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspnet-pvc
  labels:
    type: local-pvc # Label to match the Pod
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  selector:
    matchLabels:
      type: local-pv # Label to match the PV