apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: cont-nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
