version: "3"

services:
  catalogdb:
    image: mongo
    restart: always
    container_name: catalogdb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "5000:8080"

volumes:
  mongo_data:
