version: "3.4"

services:
  frontend:
    image: pizzamvcfrontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - backendUrl=http://backend
    ports:
      - "5902:80"
    depends_on:
      - backend
  backend:
    image: pizzaapibackend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5900:80"
