version: "3"

volumes:
  productsdata:

networks:
  backend:

services:
  mysql:
    image: "mysql:5.7"
    volumes:
      - productsdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - bind-address=0.0.0.0

  mvc:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - backend
    ports:
      - "5000:8080"
    environment:
      - DBHOST=mysql
    depends_on:
      - mysql
